name: Generate API Docs

on:
  release:
    types: [published]
  workflow_dispatch:
  repository_dispatch:
    types: [docbox]

jobs:
  docbox:
    name: Generate API Docs
    runs-on: ubuntu-latest
    container: ghcr.io/foundeo/cfml-ci-tools/cfml-ci-tools:1.0.6
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate API Docs
        run: box run-script build:docs

      - name: Setup env.VERSION
        run: |
          echo "VERSION=`box package version`" >> $GITHUB_ENV
          echo ${{ env.VERSION }}

      - name: Upload API Docs to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: "apidocs.ortussolutions.com"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
          SOURCE_DIR: ".tmp/apidocs"
          DEST_DIR: "${{ github.repository }}/${{ env.VERSION }}" 