name: Test Suites

# We are a reusable Workflow only
on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK_URL:
        required: true
      TWILIO_ACCOUNT_SID:
        required: true
      TWILIO_AUTHTOKEN:
        required: true
      TWILIO_TEST_ACCOUNT_SID:
        required: true
      TWILIO_TEST_AUTHTOKEN:
        required: true

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    env:
      DB_USER: root
      DB_PASSWORD: root
    strategy:
      fail-fast: false
      matrix:
        cfengine: [ "lucee@5", "lucee@6", "adobe@2021", "adobe@2023" ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Setup CommandBox CLI
        uses: Ortus-Solutions/setup-commandbox@main

      - name: Install Test Harness Dependencies
        run: |
          box install

      - name: Start ${{ matrix.cfengine }} Server
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTHTOKEN: ${{ secrets.TWILIO_AUTHTOKEN }}
          TWILIO_TEST_ACCOUNT_SID: ${{ secrets.TWILIO_TEST_ACCOUNT_SID }}
          TWILIO_TEST_AUTHTOKEN: ${{ secrets.TWILIO_TEST_AUTHTOKEN }}
        run: |
          box server start cfengine=${{ matrix.cfengine }} port=49619 --noSaveSettings --debug
          # Install Adobe 2021 cfpm modules
          if [[ "${{ matrix.cfengine }}" == "adobe@2021" ]] ; then
            box run-script install:2021
          fi
          curl http://127.0.0.1:49619

      - name: Run Tests
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTHTOKEN: ${{ secrets.TWILIO_AUTHTOKEN }}
          TWILIO_TEST_ACCOUNT_SID: ${{ secrets.TWILIO_TEST_ACCOUNT_SID }}
          TWILIO_TEST_AUTHTOKEN: ${{ secrets.TWILIO_TEST_AUTHTOKEN }}
        run: |
          mkdir -p tests/results
          box testbox run --verbose outputFile=tests/results/test-results outputFormats=json,antjunit

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: tests/results/**/*.xml
          check_name: "${{ matrix.cfengine }} Test Results"

      - name: Upload Test Results to Artifacts
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: test-results-${{ matrix.cfengine }}
          path: |
            tests/results/**/*

      - name: Show Server Log On Failures
        if: ${{ failure() }}
        run: |
          box server log

      - name: Upload Debug Logs To Artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v6
        with:
          name: Failure Debugging Info - ${{ matrix.cfengine }}
          path: |
            .engine/**/logs/*
            .engine/**/WEB-INF/cfusion/logs/*

      - name: Slack Notifications
        # Only on failures and NOT in pull requests
        if: ${{ failure() && !startsWith( 'pull_request', github.event_name ) }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: coding
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'green' or '#ff00ff'
          SLACK_ICON_EMOJI: ":bell:"
          SLACK_MESSAGE: '${{ github.repository }} tests failed :cry:'
          SLACK_TITLE: ${{ github.repository }} Tests For ${{ matrix.cfengine }} failed
          SLACK_USERNAME: CI
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}