name: Test Suites

# We are a reusable Workflow only
on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK_URL:
        required: true
      TWILIO_ACCOUNT_SID:
        required: true
      TWILIO_AUTHTOKEN:
        required: true
      TWILIO_TEST_ACCOUNT_SID:
        required: true
      TWILIO_TEST_AUTHTOKEN:
        required: true

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-20.04
    env:
      DB_USER: root
      DB_PASSWORD: root
    strategy:
      fail-fast: false
      matrix:
        cfengine: [ "lucee@5", "lucee@6", "adobe@2021", "adobe@2023" ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Not Needed in this module
      #- name: Setup Database and Fixtures
      #  run: |
      #    sudo /etc/init.d/mysql start
      #    mysql -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} -e 'CREATE DATABASE coolblog;'
      #    mysql -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} < tests/resources/coolblog.sql

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Setup CommandBox CLI
        uses: Ortus-Solutions/setup-commandbox@main

      # Not Needed in this module
      #- name: Setup Environment For Testing Process
      #  working-directory: ./test-harness
      #  run: |
      #    # Setup .env
      #    touch .env
      #    # ENV
      #    printf "DB_HOST=localhost\n" >> .env
      #    printf "DB_DATABASE=mydatabase\n" >> .env
      #    printf "DB_DRIVER=MySQL\n" >> .env
      #    printf "DB_USER=${{ env.DB_USER }}\n" >> .env
      #    printf "DB_PASSWORD=${{ env.DB_PASSWORD }}\n" >> .env
      #    printf "DB_CLASS=com.mysql.cj.jdbc.Driver\n" >> .env
      #    printf "DB_BUNDLEVERSION=8.0.19\n" >> .env
      #    printf "DB_BUNDLENAME=com.mysql.cj\n" >> .env

      - name: Cache CommandBox Dependencies
        uses: actions/cache@v1
        if: ${{ true }}
        with:
          path: ~/.CommandBox/artifacts
          key: ${{ runner.OS }}-commandbox-cache-${{ hashFiles( 'box.json' ) }}-${{ hashFiles( 'box.json' ) }}
          restore-keys: |
            ${{ runner.OS }}-commandbox-cache-${{ hashFiles( 'box.json' ) }}-${{ hashFiles( 'box.json' ) }}

      - name: Install Test Harness Dependencies
        run: |
          box install

      - name: Start ${{ matrix.cfengine }} Server
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTHTOKEN: ${{ secrets.TWILIO_AUTHTOKEN }}
          TWILIO_TEST_ACCOUNT_SID: ${{ secrets.TWILIO_TEST_ACCOUNT_SID }}
          TWILIO_TEST_AUTHTOKEN: ${{ secrets.TWILIO_TEST_AUTHTOKEN }}
        run: |
          box server start cfengine=${{ matrix.cfengine }} port=49619 --noSaveSettings --debug
          # Install Adobe 2021 cfpm modules
          if [[ "${{ matrix.cfengine }}" == "adobe@2021" ]] ; then
            box run-script install:2021
          fi
          curl http://127.0.0.1:49619

      - name: Run Tests
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTHTOKEN: ${{ secrets.TWILIO_AUTHTOKEN }}
          TWILIO_TEST_ACCOUNT_SID: ${{ secrets.TWILIO_TEST_ACCOUNT_SID }}
          TWILIO_TEST_AUTHTOKEN: ${{ secrets.TWILIO_TEST_AUTHTOKEN }}
        run: |
          mkdir -p tests/results
          box testbox run --verbose outputFile=tests/results/test-results outputFormats=json,antjunit

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: tests/results/**/*.xml
          check_name: "${{ matrix.cfengine }} Test Results"

      - name: Upload Test Results to Artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results-${{ matrix.cfengine }}
          path: |
            tests/results/**/*

      - name: Show Server Log On Failures
        if: ${{ failure() }}
        run: |
          box server log

      - name: Upload Debug Logs To Artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: Failure Debugging Info - ${{ matrix.cfengine }}
          path: |
            .engine/**/logs/*
            .engine/**/WEB-INF/cfusion/logs/*

      - name: Slack Notifications
        # Only on failures and NOT in pull requests
        if: ${{ failure() && !startsWith( 'pull_request', github.event_name ) }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: coding
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'green' or '#ff00ff'
          SLACK_ICON_EMOJI: ":bell:"
          SLACK_MESSAGE: '${{ github.repository }} tests failed :cry:'
          SLACK_TITLE: ${{ github.repository }} Tests For ${{ matrix.cfengine }} failed
          SLACK_USERNAME: CI
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}